---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "480p-com"
spec:
  secretName: "480p-com-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "480p.com"
  dnsNames:
    - "480p.com"
    - "*.480p.com"
