---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app beszel-agent
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: beszel-agent
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      beszel-agent:
        type: daemonset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: henrygd/beszel-agent
              tag: latest@sha256:bc6c4068ce99d20e66ea28830d853339145552704497496d1d0cfd6999413070
            envFrom:
              - secretRef:
                  name: beszel-agent-secret
            env:
              - name: LISTEN
                value: &LISTEN 45876
            ports:
              - containerPort: *LISTEN
                hostPort: *LISTEN
        pod:
          hostNetwork: true
